services:
  app:
    image: yourusername/uchet_bot:latest
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["mongo", "--eval", "db.runCommand({ ping: 1 }).ok", "--username", "admin", "--password", "password", "--host", "localhost", "--port", "27017"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s 

volumes:
  mongodb_data: