services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy  
    volumes:
      - .:/app
    env_file:
      - .env  
    command: /bin/sh -c "alembic upgrade head && uvicorn app.bot.init:app --host 0.0.0.0 --port 8000"

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "/usr/bin/mongo", "--eval", "db.runCommand({ ping: 1 }).ok", "--username", "admin", "--password", "password", "--host", "localhost", "--port", "27017"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mongodb_data: