"""fix

Revision ID: a9c74dcbeb90
Revises: 776cd3391c6b
Create Date: 2025-07-17 13:29:38.320112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9c74dcbeb90'
down_revision: Union[str, Sequence[str], None] = '776cd3391c6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sold_devices', sa.Column('sale_price', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sold_devices', 'sale_price')
    # ### end Alembic commands ###
